services:
  pfgroup_db:
    container_name: pfgroup_db
    restart: unless-stopped
    image: postgres:15-alpine3.22
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - db_data:/var/lib/postgresql/data
    expose:
      - 5432
  pfgroup_api:
    container_name: pfgroup_api
    restart: unless-stopped
    build: ../project
    env_file:
      - .env
    depends_on:
      pfgroup_db:
        condition: service_healthy
    ports:
      - ${API_PORT}:3000

volumes:
  db_data: {}
